before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - master
    - publish
env:
    global:
    # this value is auto-created by shAesEncryptTravis
    - secure: Hxc56I78bgyaw2+XWphQNJHU96ff7/lS1RCagkgfStZaSJlW3JLYjTPhrDRvfXdnJq05Pz5LWEnLhbn7KPT0z6ysxy8uuKTVASnQgOnZy27taKyAQJNS/HBmpbhxxNoAR20yqbGAI12rlRsm1OnbkFDkTrZDEhUUxVcd39YLpD66fIfKYwtHYehFtu44tiKE53d/5VLh63919+tW4/E9oLpbJRn1kNn05R2hlZLDre3779QAD+cvLpDPcF5rYHGz/S1Td5Hd6oCENCega1i/bOcLTYtYPGGTURxBq7MZhIsGBpAnWr/jwIwu8fDsDBRL1NObfmB46gVc1czPfiXWmvZtNzyUdEklxOX90Ti4QZgDjZQEQH8CW6yIQOlOpkignBOPN/ouKTb3p86RHFrZQPzvbniRbT/kvgxY4SzHMvLvDMVxaRASm9LyIpXXzndFJK/Yn+eXndiOSg6fSNgMr97v14nrpx0yZ0Mc/emDYj9N7u2o0jCUY0bfOseR4IUTBsXLZTDQPKOcmNYhBPVhBuQtgEkaZer8L3qjxXqG9fCRs2ugPowMaLzvwFitBL2PmPTairWIQCT33DBmTohRi1faKfSOcH5w61iyA8XStTyzhmpYgwUYhiXOTSPy0gKIJhL92aoPL5lTtXBc5CsOsi8xtpwDuCFcysQp+T6vcto= # CRYPTO_AES_KEY
    # this value is auto-created by shAesEncryptTravis
    # - CRYPTO_AES_ENCRYPTED_SH: MDk0YWRiNDhjZmYzN2MxNDQ5NWNkNTVlZDliYjMwZDk=UaqWTrUhtFScP658DGqjrJlCOKFuqZyhUTW5OZmdj89noO/uA/xV40tTWuZAw5lNuFr+ihXVhUoZJ8d0Tw0RXIrQnFFu5Y7QhYLHu74dN/bWLKUcm0pvjgqlgfDIrfNx6Ud3ewlbw73yjDHL9scq2VKlWysBZRsYmVSJDN/HS98QCavSPcgKFFAsxtD+4yvgucNHOGnV5DGM3g7nD8niB2zFtDwXIp4zApXEKsS5AQyoNH7ZFeDugp/fMVLTlUMA/O6NdcPk23Qh+DBi5Xqtu2e/sXoTLgZSnqUbKGUtCkni/4LrWoSr5IxxGWgrMM3fE6dETnhtVpn1hLKZtGQ0LbfjFiopBbyZGxDOFrPWTr/MxXhhalhYIgWwbf0Sy39T48imR00Ac647SMfck9QMUpSo3l7IgtDyejYvxEUHYR1/i86aDUIkHf+KC0q2Sa8zY7vN/CzW+KOxvHiFBfG5yC2yq4rEqCAEDwY0mkz4YHSStaAtUQMK0NL89DnhlVy9zMaEuFKRL1QE1QTI+6BapUPb+cXy4NAS0N5CQ7xG0UKMKMyOoU9IxEaZvfqfqmEGJaqNK0EXl0iKSmcHr8hdZhQSI3fuzR5wkyE821GLXITilJXWjK0gmUZTq+HIvCckC1k/6y0kYZOSq6aZimPLAOIKNsaD/XbdKOsLJKV9duNPmlfX87FJMEx1jlEne1tYMM2fGNIKnzWUw0BkrAU2NEYrC/NsOOGLZmckxnN3iJUFty60jRKRwNhnyRCX8AN+fwrTych/CfI83BsSAgIWh12jjHk6fVDXnrviQiCpQYKDZzjdUe9ASEILzeSkPiDTuyTP8CZGolJvVX86QtDhS16V9pJ7KKSG4QHaBCoqEUM= # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    # - 6
    - node
script:
    - npm run build-ci
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
