before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
    # bug-workaround for "npm install [package name] removes packages"
    # https://github.com/npm/npm/issues/17379
    # https://github.com/travis-ci/travis-ci/issues/4653
    - dpkg --compare-versions `npm -v` ge 5.8 || npm i -g npm@^5.8
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.electron
    - docker.latest
    - docker.tmp
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: Tl9Znmfv9OMANn4WeeeJnVH7ADV81rM0rkHiyvIEl4jH6dd0oW7HZriwQk6KhhXtaY9CRcByZ2ldECq7Nufs705r3TxKWcJqZiFOCjdjr28yo2x7Z9x4m9DWlcWAdVxvqae2pba1wJBgT3/3/aAuvtfa7h/LYNcbz5KFvn+RxSSaNmdeJVcTGehR6gHHdGS43+JznQTHmAELs5R3B0PW/4hfcwc5HLpCKMOgx4E1UwgVGPTdKdKuIo38vtlSqPtE8uenEh5FiD8p1G/CRH/NDkQd6f3fHXwPwp3FVf3fVdFioOSX3/YmNNI3Ph5TIYR1ezcByhItNlORgN9ttbC6dMubfYAAFACo38FEuwcnkMRCpMFSD5hqHZbQGTG0onrUhPSVZcvoGuPv/LmtIOBw9yoBmyr8CQaq0mamcjNCl6nXbm9dH+XMotKFagGNQHIBS2HO9UhFIRtNywYeYgDP7SbsYldsJXtOuZKiWxOPjOic25eHuVE3PLazYp7dhmiuuMu1QvrCY4vvOnjU/1kEzRB3tvG/wA1wz74JtRLEhJgWCowuvpB+5bZj6kvqgtRZPr7pHFF63vaDNN9GrgSyoTd53Eqx7ZrstSZ7mGjClId14lcs4TuPfTPBs3izIIMYS+SbRNJqA0HI7IfEfXM0lmyy611QIKv44ey8yOls/p4= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    # - 8
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
